### ISSUE TITLE
Unexpected unicode value for glyph ki-adjust: "\ea001"

### ISSUE THREAD

**Issue by juliettef** [SamBrishes/kenney-icon-font#2]
As it's the last glyph, I would have expected it to be "\e9c7" as it's listed after "\e9c6" in the svg file. This could potentially overlap with other font ranges when merging fonts.

**Comment by SamBrishes** [comment]
Thanks! I forgot to reset this value, i will change (re-order) this unicode value with the next update.

**Comment by SamBrishes** [comment]
Fixed in Version 0.2.0.
