### ISSUE TITLE
Add LT, RT, LB, RB icons for Xbox controller

### ISSUE THREAD

**Issue by mbabuskov** [SamBrishes/kenney-icon-font#4]
Hi,
the icons are great. I see that you have X,Y,A,B buttons, but missing LT, RT, LB, RB which are used for right/left trigger/bumper on Xbox 360 controller, which is a widely used controller.

Thanks.

**Comment by SamBrishes** [comment]
Hello,

Version 0.2.0 is almost finished, but i will try to add this icons too.

Thanks for the Request.

**Comment by SamBrishes** [comment]
Icons added in Version 0.2.0
